//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinh
    {
        public int Id { get; set; }
        public string MaCauHinh { get; set; }
        public string TenCauHinh { get; set; }
        public Nullable<int> IdCha { get; set; }
        public Nullable<int> EnumLoai { get; set; }
        public Nullable<int> IdNguoiTao { get; set; }
        public Nullable<int> IdNguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> IsHienThi { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
