//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyLamGiaSu
    {
        public int Id { get; set; }
        public Nullable<int> IdTinh { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> GiongNoi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> CMND { get; set; }
        public Nullable<int> NguyenQuan { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<int> DienThoai { get; set; }
        public string AnhThe { get; set; }
        public string AnhBangCap { get; set; }
        public string Truong { get; set; }
        public string NganhHoc { get; set; }
        public Nullable<int> NamTotNghiep { get; set; }
        public Nullable<int> NgheNghiep { get; set; }
        public Nullable<int> TrinhDo { get; set; }
        public string UuDiem { get; set; }
        public string MonDay { get; set; }
        public string LopDay { get; set; }
        public string KhuVucDay { get; set; }
        public string ThoiGianDay { get; set; }
        public Nullable<int> SoBuoiDay { get; set; }
        public Nullable<decimal> MucLuong { get; set; }
        public string YeuCau { get; set; }
        public Nullable<bool> IsHienThi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
