//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyNhanLop
    {
        public int Id { get; set; }
        public Nullable<int> MaSoLop { get; set; }
        public Nullable<int> DienThoai { get; set; }
        public Nullable<int> HinhThucNhan { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<decimal> LePhi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> IdNguoiDuyet { get; set; }
        public string GioNhan { get; set; }
        public string YeuCauThem { get; set; }
        public Nullable<decimal> HoanPhi { get; set; }
        public Nullable<System.DateTime> NgayTraLop { get; set; }
    }
}
