//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rounter
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public Nullable<int> IdThamChieu { get; set; }
        public Nullable<int> EnumLoai { get; set; }
        public string TenLoai { get; set; }
    }
}
